// -------------------------------------------------------------------------------------------------
//  <copyright file="HtmlReportGenerator.cs" company="Starion Group S.A.">
// 
//    Copyright 2019-2025 Starion Group S.A.
// 
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
// 
//        http://www.apache.org/licenses/LICENSE-2.0
// 
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.
// 
//  </copyright>
//  ------------------------------------------------------------------------------------------------

namespace DEHBSMI.Tools.Generators
{
    using System.IO;
    using System;

    using CDP4Common.EngineeringModelData;

    using Microsoft.Extensions.Logging;
    using Microsoft.Extensions.Logging.Abstractions;
    using System.Collections.Generic;

    /// <summary>
    /// The purpose of the <see cref="HtmlReportGenerator"/> is to generate an HTML based
    /// report from an ECSS-E-TM-10-25 model according the BSMI structure
    /// </summary>
    public class HtmlReportGenerator : IHtmlReportGenerator
    {
        /// <summary>
        /// The <see cref="ILogger"/> used to log
        /// </summary>
        private readonly ILogger<HtmlReportGenerator> logger;

        /// <summary>
        /// Initializes a new instance of the <see cref="HtmlReportGenerator"/> class.
        /// </summary>
        /// <param name="loggerFactory">
        /// The (injected) <see cref="ILoggerFactory"/> used to set up logging
        /// </param>
        public HtmlReportGenerator(ILoggerFactory loggerFactory = null)
        {
            this.logger = loggerFactory == null ? NullLogger<HtmlReportGenerator>.Instance : loggerFactory.CreateLogger<HtmlReportGenerator>();
        }

        /// <summary>
        /// Generates an HTML based BSMI export
        /// </summary>
        /// <param name="iteration">
        /// The <see cref="Iteration"/> that contains the data that is to be generated
        /// </param>
        /// <param name="specifications">
        /// The <see cref="RequirementsSpecification"/>s that need to be taken into account for report generation
        /// </param>
        /// <param name="outputReport">
        /// The <see cref="FileInfo"/> where the result is to be generated
        /// </param>
        /// <param name="unallocatedBsmiCode">
        /// The value for the BSMI parameter for unallocated requirements
        /// </param>
        public void Generate(Iteration iteration, IEnumerable<RequirementsSpecification> specifications, FileInfo outputReport, string unallocatedBsmiCode)
        {
            this.logger.LogInformation("Start Generating the HTML BMSI Report");

            throw new NotImplementedException();
        }

        /// <summary>
        /// Verifies whether the extension of the <paramref name="outputPath"/> is valid or not
        /// </summary>
        /// <param name="outputPath">
        /// The subject <see cref="FileInfo"/> to check
        /// </param>
        /// <returns>
        /// A Tuple of bool and string, where the string contains a description of the verification.
        /// Either stating that the extension is valid or not.
        /// </returns>
        public Tuple<bool, string> IsValidReportExtension(FileInfo outputPath)
        {
            if (outputPath == null)
            {
                throw new ArgumentNullException(nameof(outputPath));
            }

            if (outputPath.Extension == ".html")
            {
                return new Tuple<bool, string>(true, ".html is a supported report extension");
            }

            return new Tuple<bool, string>(false,
                $"The Extension of the output file '{outputPath.Extension}' is not supported. Supported extensions is '.html'");
        }

        /// <summary>
        /// Queries the name of the report type that is generated by the current <see cref="IReportGenerator"/>
        /// </summary>
        /// <returns>
        /// human-readable name of the report type
        /// </returns>
        public string QueryReportType()
        {
            return "html";
        }
    }
}
