// -------------------------------------------------------------------------------------------------
//  <copyright file="IReportGenerator.cs" company="Starion Group S.A.">
// 
//    Copyright 2019-2025 Starion Group S.A.
// 
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
// 
//        http://www.apache.org/licenses/LICENSE-2.0
// 
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.
// 
//  </copyright>
//  ------------------------------------------------------------------------------------------------

namespace DEHBSMI.Tools.Generators
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    
    using CDP4Common.EngineeringModelData;

    /// <summary>
    /// The purpose of the <see cref="IReportGenerator"/> is to generate a BSMI report based on
    /// <see cref="ElementDefinition"/>s, <see cref="Requirement"/>s and <see cref="BinaryRelationship"/>s
    /// </summary>
    public interface IReportGenerator
    {
        /// <summary>
        /// Generates the BSMI export
        /// </summary>
        /// <param name="iteration">
        /// The <see cref="Iteration"/> that contains the data that is to be generated
        /// </param>
        /// <param name="specifications">
        /// The <see cref="RequirementsSpecification"/>s that need to be taken into account for report generation
        /// </param>
        /// <param name="outputReport">
        /// The <see cref="FileInfo"/> where the result is to be generated
        /// </param>
        /// <param name="unallocatedBsmiCode">
        /// The value for the BSMI parameter for unallocated requirements
        /// </param>
        public void Generate(Iteration iteration, IEnumerable<RequirementsSpecification> specifications, FileInfo outputReport, string unallocatedBsmiCode);
        
        /// <summary>
        /// Verifies whether the extension of the <paramref name="outputPath"/> is valid or not
        /// </summary>
        /// <param name="outputPath">
        /// The subject <see cref="FileInfo"/> to check
        /// </param>
        /// <returns>
        /// A Tuple of bool and string, where the string contains a description of the verification.
        /// Either stating that the extension is valid or not.
        /// </returns>
        public Tuple<bool, string> IsValidReportExtension(FileInfo outputPath);

        /// <summary>
        /// Queries the name of the report type that is generated by the current <see cref="IReportGenerator"/>
        /// </summary>
        /// <returns>
        /// human-readable name of the report type
        /// </returns>
        public string QueryReportType();
    }
}